// <auto-generated />
using System;
using EventPlanner.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventPlanner.Migrations
{
    [DbContext(typeof(EventPlannerDbContext))]
    [Migration("20240413010751_Next Migration")]
    partial class NextMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("EventPlanner.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            EndDate = new DateTime(2024, 5, 13, 21, 7, 51, 226, DateTimeKind.Local).AddTicks(1213),
                            EventDescription = "A lowkey party in the center of the Pacific Ocean.",
                            EventName = "Danny's Graduation Party",
                            Location = "Pacific Ocean",
                            StartDate = new DateTime(2024, 5, 12, 21, 7, 51, 226, DateTimeKind.Local).AddTicks(1171)
                        },
                        new
                        {
                            EventId = 2,
                            EndDate = new DateTime(2024, 5, 18, 21, 7, 51, 226, DateTimeKind.Local).AddTicks(1217),
                            EventDescription = "An EDM concert at Bogart's.",
                            EventName = "EDM Concert",
                            Location = "2621 Short Vine St, Cincinnati, OH 45219",
                            StartDate = new DateTime(2024, 5, 17, 21, 7, 51, 226, DateTimeKind.Local).AddTicks(1215)
                        },
                        new
                        {
                            EventId = 3,
                            EndDate = new DateTime(2024, 5, 20, 21, 7, 51, 226, DateTimeKind.Local).AddTicks(1221),
                            EventDescription = "A retirement party for Joe.",
                            EventName = "Retirement Party",
                            Location = "400 Broadway, Cincinnati, OH 45202",
                            StartDate = new DateTime(2024, 5, 19, 21, 7, 51, 226, DateTimeKind.Local).AddTicks(1219)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
